version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10-stretch
    steps:
      - checkout

      - restore_cache:
          keys:
          - node-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - node-{{ .Branch }}-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: node-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm run lint
      # todo: - run: npm run test
      - run: npm run build

      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10-stretch
    steps:
      - attach_workspace:
          at: ~/

      # add publish ssh key
      - add-ssh-keys:
          fingerprints:
            - "f9:76:ad:2d:14:6d:d1:f2:f1:ba:97:c8:9a:38:a2:a8"
      - run:
          name: keyscan
          command: |
            if [ ! -d ~/.ssh ]; then
              mkdir ~/.ssh
            fi
            ssh-keyscan github.com >> ~/.ssh/known_hosts

      - run:
          name: publisih
          command: |
            cd dist && git init
            git config --global user.email "efredin+circleci@gmail.com"
            git config --global user.name "CircleCI"
            git remote add production git@github.com:efredin/efredin.github.io.git
            git add .
            git commit -m "$CIRCLE_BRANCH build#CIRCLE_BUILD_NUM" --allow-empty
            git push --force production master

workflows:
  version: 2
  testfirelabs-vnext-latest:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
